name: demo
on: [ workflow_dispatch ]
jobs:
  # x86_64
  x64:
    name: Checkout x64 support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: uname -a
  aarch64:
    name: Checkout aarch64 support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - uses: uraimo/run-on-arch-action@v2.2.0
      - uses: AlexTalker/run-on-arch-action@manjarolinux-support
        id: runcmd
        with:
          arch: aarch64
#           distro: archarm_latest
          distro: manjarolinux_latest
          run: |
            uname -a;
            sudo pacman -Syu;
            pacman -Qi pacman;
