name: libvirt
on: [ workflow_dispatch ]
jobs:
  # x86_64
  x64:
    name: Checkout libvirt setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - run: uname -a; df -h; cat /etc/os-release; pwd; mount
      - run: sudo DEBIAN_FRONTEND=noninteractive apt update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt upgrade
      - run: sudo DEBIAN_FRONTEND=noninteractive apt install libvirt-daemon libvirt-daemon-system libvirt-clients 
      - run: systemctl status libvirtd
      - run: sudo virsh -c qemu:///system list --all
      - run: sudo DEBIAN_FRONTEND=noninteractive apt install qemu-system-misc u-boot-qemu
      - run: sudo virsh -c qemu:///system capabilities
      - run: sudo DEBIAN_FRONTEND=noninteractive apt install podman podman-compose
      - run: podman run --rm hello-world
      - run: bash libvirt/setup.sh
      - run: bash libvirt/run.sh vagrant version
      - name: Attempt to download RISCV64 box
        uses: actions/download-artifact@v4.1.8
        with:
          run-id: "11352522785"
          github-token: ${{ github.token }}
          repository: "AlexTalker/vagrant-libvirt-ubuntu-riscv-box-draft"
          path: libvirt/workdir/
      - run: ls -lah libvirt/workdir/*
      - run: bash libvirt/run.sh -c 'ls -lah .'
      - run: bash libvirt/run.sh vagrant box add ubuntu_riscv_2024 vagrant-libvirt-ubuntu/ubuntu-riscv-24.04.1.box
      - run: bash libvirt/run.sh vagrant box list
      - run: bash libvirt/run.sh vagrant up
      - run: bash libvirt/run.sh vagrant status
