name: libvirt
on: [ workflow_dispatch ]
jobs:
  # x86_64
  x64:
    name: Checkout libvirt setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: uname -a; df -h; cat /etc/os-release;

