name: libvirt
on: [ workflow_dispatch ]
jobs:
  # x86_64
  x64:
    name: Checkout libvirt setup
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - run: uname -a; df -h; cat /etc/os-release; pwd; mount
      - run: sudo DEBIAN_FRONTEND=noninteractive apt update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt upgrade
      - run: sudo DEBIAN_FRONTEND=noninteractive apt install libvirt-daemon libvirt-daemon-system libvirt-clients 
      - run: systemctl status libvirtd
      - run: sudo virsh -c qemu:///system list --all
      - run: sudo DEBIAN_FRONTEND=noninteractive apt install qemu-system-misc u-boot-qemu
      - run: sudo virsh -c qemu:///system capabilities

