name: nbd
on: [ workflow_dispatch ]
jobs:
  # x86_64
  x64:
    name: Checkout x64 support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: uname -a; modinfo nbd; ls -lah /sys/module/ndb/;

